name: Deploy SGR para o Azure WebApp Service

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v6

      - name: Configurar .NET 10
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Restaurar Dependências
        run: dotnet restore SGR/SGR.csproj

      - name: Construção do Projeto
        run: dotnet build SGR/SGR.csproj --configuration Release --no-restore

      - name: Publicar Artefatos
        run: dotnet publish SGR/SGR.csproj --configuration Release --output ./publish --no-build

      - name: Implementar para Azure App Service
        uses: azure/webapps-deploy@v2.2.19
        with:
          app-name: sgr-web
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish